[package]
name = "rss-client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = "0.19.3"
robot_sweet_shop = {path="../robot_sweet_shop"}
wasm-bindgen-futures = "*"
reqwasm = "*"
futures ="*"
